#!/bin/bash

if [ -f $DIR_SCRIPT/config/default ]; then
    while read -r line; do eval $line; done < $DIR_SCRIPT/config/default
fi

if [ -f $DIR_SCRIPT/settings ]; then
    while read -r line; do eval $line; done < $DIR_SCRIPT/settings
fi

if [[ $AIUR_SAFE_MODE == true ]]; then
    echo "--- SAFE MODE ---"
    echo
fi

safemode(){
    if [[ $AIUR_SAFE_MODE != true ]]; then $@; fi
}

get_file_size(){
    stat --format=%s $1
}

check_in_array(){
    set +e
    local e match="$1"
    shift
    for e; do [[ "$e" == "$match" ]] && return 0; done
    return 1
}

display_numerate_list(){
    local item n=1

    for item; do
        echo "$n $item"
        n=$((1+$n))
    done
}
