#!/bin/bash

safemode(){
    if [[ $AIUR_SAFE_MODE != true ]]; then $@; fi
}

if [[ $AIUR_SAFE_MODE == true ]]; then
    echo "--- SAFE MODE ---"
    echo
fi

get_file_size(){
    stat --format=%s $1
}
