#! /bin/bash

cat << EOM
Lista de comandos:
    version     Display $APP_NAME version
    enc         EncFS related tools
    image       $APP_NAME image optimize ORIGEN
    q-ping      Perform a quick network test and dispatch a notification
    top         Open top in a new window
    mem         $APP_NAME mem proc <proc_name>
                $APP_NAME mem app1
    unity-git   Fetch .gitignore file for Unity from Github
    sync        $APP_NAME sync pull // trae cambios del remoto
                $APP_NAME sync push // envía cambios al remoto
    kill        $APP_NAME kill <proc_name> // sends a SIGKILL to the process
    help
EOM