#! /bin/bash

cat << EOM
Lista de comandos:
    version     Display $APP_NAME version
    enc         EncFS related tools
    image       $APP_NAME image optimize ORIGEN
    q-ping      Perform a quick network test and dispatch a notification
    top         Open top in a new window
    help
EOM