#! /bin/bash
set -e

APP_NAME=aiur
DIR_SCRIPT=$(dirname $(readlink -f $0))

echo "For Aiur!"
echo

. $DIR_SCRIPT/includes/common

if [[ $1 == 'version' ]]; then
    echo "Aiur version $APP_VERSION"

elif [[ $1 == 'enc' ]]; then
    . $DIR_SCRIPT/includes/enc

elif [[ $1 == 'image' ]]; then
    . $DIR_SCRIPT/includes/image

    if [[ $2 == 'optimize' ]]; then
        echo "Reduciendo el tamaño de $3"
        SOURCE=$(pwd)/$3

        if [ -d $SOURCE ]; then
            reduce_image_rec $SOURCE
        else
            echo 'No es directorio.'
        fi
    else
        echo "No se hizo nada."
        exit 1
    fi

elif [[ $1 == 'q-ping' ]]; then
    result=$(ping -q -c 4 yahoo.com)

    while IFS= read -r line ; do
        if [[ $line =~ "packet loss" ]]; then
            notify-send "Ping to yahoo" "$line"
        fi
    done <<< "$result"

elif [[ $1 == 'top' ]]; then
    $TERMINAL -- top -e m -E g

elif [[ $1 == 'mem' ]]; then
    . $DIR_SCRIPT/includes/mem.sh

elif [[ $1 == 'kill' ]]; then
    mem_used=$($0 mem proc $2)
    notify-send "Killing <$2>" "$mem_used"
    killall -s SIGKILL $2

elif [[ $1 == 'test' ]]; then
    echo 'testing:'

elif [[ $1 == 'help' ]]; then
    . $DIR_SCRIPT/includes/help

else
    echo "No se reconoce el comando $1."
fi

echo
