#! /bin/sh
set -e

WORK_DIR=$HOME/storage/misc
APP_NAME=aiur

echo "For Aiur!"
echo

if [[ $1 == "enable" ]]; then
    echo "Montando $2"

    if [ -d $WORK_DIR/.$2_encfs ]; then
        echo "yeah"
        mkdir -p $WORK_DIR/$2
        encfs $WORK_DIR/.$2_encfs $WORK_DIR/$2

        echo "Open folder? (y/N)"
        read OPEN
        if [[ $OPEN == "y" ]]; then
            gnome-open $WORK_DIR/$2
        fi
        echo "Hecho."
    else
        echo "No encuentra .$2_encfs"
        exit 1
    fi

elif [[ $1 == "disable" ]]; then
    if [[ $1 == "disable" ]]; then
        echo "Desmontando $2"
        if [ -d $WORK_DIR/$2 ]; then
            fusermount -u $WORK_DIR/$2
            echo "Hecho."
        else
            echo "No existe $WORK_DIR/$2"
            exit 1
        fi
    fi

elif [[ $1 == 'clean' ]]; then
    THUMB_ROUTE=$HOME/.cache/thumbnails
    echo "Borrando thumbnails"
    rm -rf $THUMB_ROUTE
    echo "Hecho."

elif [[ $1 == 'help' ]]; then
    cat << EOM
Lista de comandos:
    enable      $APP_NAME enable [name]      
    disable     $APP_NAME disable [dirname]
    clean       $APP_NAME clean
    help        
EOM

else
    echo "No se reconoce el comando $1."
fi

echo
